### ISSUE TITLE
Unable to dump loot tables

### ISSUE THREAD

**Issue by dshadowwolf** [Leviathan143/LootTweaker#2]
Unsure if this is something in your code or not, but "An unknown error occurred while attempting to perform this command" in both SMP and SSP for "/mt loottables all"

Stack dump below. (I found a nifty way to do a spoiler-like bit here, yay!)
<details>
  <summary>[00:34:21] [Server thread/WARN]: Couldn't process command: 'mt loottables all'
java.lang.AssertionError</summary><p>
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:733) ~[TypeAdapters$EnumTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapters$26.create(TypeAdapters.java:762) ~[TypeAdapters$26.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48) ~[ArrayTypeAdapter$1.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52) ~[CollectionTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.toJson(Gson.java:593) ~[Gson.class:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:486) ~[Gson.class:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:465) ~[Gson.class:?]
	at com.google.gson.Gson$2.serialize(Gson.java:132) ~[Gson$2.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.serialize(LootTable.java:213) ~[bap$a.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.serialize(LootTable.java:201) ~[bap$a.class:?]
	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.toJson(Gson.java:593) ~[Gson.class:?]
	at com.google.gson.Gson.toJson(Gson.java:572) ~[Gson.class:?]
	at com.google.gson.Gson.toJson(Gson.java:527) ~[Gson.class:?]
	at com.google.gson.Gson.toJson(Gson.java:507) ~[Gson.class:?]
	at leviathan143.loottweaker.common.LootUtils.writeTableToJSON(LootUtils.java:81) ~[LootUtils.class:?]
	at leviathan143.loottweaker.common.LootUtils.writeTableToJSON(LootUtils.java:71) ~[LootUtils.class:?]
	at leviathan143.loottweaker.common.LootUtils.writeTableToJSON(LootUtils.java:66) ~[LootUtils.class:?]
	at leviathan143.loottweaker.common.commands.CommandLootTables.execute(CommandLootTables.java:32) ~[CommandLootTables.class:?]
	at minetweaker.MineTweakerImplementationAPI$3.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$3.class:?]
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:122) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
</p></details>

**Comment by dshadowwolf** [comment]
Stack Dump from 0.0.2 showing similar

<details>
<summary>[15:03:55] [Server thread/WARN]: Couldn't process command: 'mt loottables all'</summary><p>
java.lang.AssertionError
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:733) ~[TypeAdapters$EnumTypeAdapter.class:?]
	at com.google.gson.internal.bind.TypeAdapters$26.create(TypeAdapters.java:762) ~[TypeAdapters$26.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48) ~[ArrayTypeAdapter$1.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52) ~[CollectionTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[ReflectiveTypeAdapterFactory.class:?]
	at com.google.gson.Gson.getAdapter(Gson.java:356) ~[Gson.class:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:55) ~[TypeAdapterRuntimeTypeWrapper.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) ~[CollectionTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.toJson(Gson.java:593) ~[Gson.class:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:486) ~[Gson.class:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:465) ~[Gson.class:?]
	at com.google.gson.Gson$2.serialize(Gson.java:132) ~[Gson$2.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.serialize(LootTable.java:213) ~[bap$a.class:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.serialize(LootTable.java:201) ~[bap$a.class:?]
	at com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.toJson(Gson.java:593) ~[Gson.class:?]
	at com.google.gson.Gson.toJson(Gson.java:572) ~[Gson.class:?]
	at com.google.gson.Gson.toJson(Gson.java:527) ~[Gson.class:?]
	at com.google.gson.Gson.toJson(Gson.java:507) ~[Gson.class:?]
	at leviathan143.loottweaker.common.LootUtils.writeTableToJSON(LootUtils.java:84) ~[LootUtils.class:?]
	at leviathan143.loottweaker.common.LootUtils.writeTableToJSON(LootUtils.java:72) ~[LootUtils.class:?]
	at leviathan143.loottweaker.common.LootUtils.writeTableToJSON(LootUtils.java:67) ~[LootUtils.class:?]
	at leviathan143.loottweaker.common.commands.CommandLootTables.execute(CommandLootTables.java:32) ~[CommandLootTables.class:?]
	at minetweaker.MineTweakerImplementationAPI$3.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$3.class:?]
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:122) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[15:03:55] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
</p></details>

**Comment by Leviathan143** [comment]
Discovered to be an issue with EnderIO. See [SleepyTrousers/EnderIO#3927](https://github.com/SleepyTrousers/EnderIO/issues/3927)  
I am currently working with the EIO devs to fix this issue.

**Comment by Leviathan143** [comment]
The EIO devs have merged my PR. This issue should be resolved in the next version of EnderIO.
