### ISSUE TITLE
Failure to export several loot tables with Travellers Backpacks installed

### ISSUE THREAD

**Issue by Mnky313** [Leviathan143/LootTweaker#74]
Running any command to export certain loot tables (including /ct loottables all)
These are the vanilla tables that don't export:
abandoned_mineshaft
simple_dungeon
stronghold_corridor
stronghold_crossing
stronghold_library
village_blacksmith

results in error in console (below) and an empty json file

Server Console Log:
`[17:57:03] [Server thread/WARN] [leviathan143.loottweaker.common.lib.LootTableDumper]: Failed to dump loot table minecraft:chests/village_blacksmith
java.lang.IllegalArgumentException: Don't know how to serialize com.tiviacz.travellersbackpack.common.LootEntryItemStack@5b5ba0b7
        at net.minecraft.world.storage.loot.LootEntry$Serializer.serialize(LootEntry.java:113) ~[bfr$a.class:?]
        at net.minecraft.world.storage.loot.LootEntry$Serializer.serialize(LootEntry.java:45) ~[bfr$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[TreeTypeAdapter.class:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[TypeAdapterRuntimeTypeWrapper.class:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[CollectionTypeAdapterFactory$Adapter.class:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[CollectionTypeAdapterFactory$Adapter.class:?]
        at com.google.gson.Gson.toJson(Gson.java:669) ~[Gson.class:?]
        at com.google.gson.Gson.toJsonTree(Gson.java:562) ~[Gson.class:?]
        at com.google.gson.Gson.toJsonTree(Gson.java:541) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.world.storage.loot.LootPool$Serializer.serialize(LootPool.java:156) ~[bfq$a.class:?]
        at net.minecraft.world.storage.loot.LootPool$Serializer.serialize(LootPool.java:138) ~[bfq$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[TreeTypeAdapter.class:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[TypeAdapterRuntimeTypeWrapper.class:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[CollectionTypeAdapterFactory$Adapter.class:?]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[CollectionTypeAdapterFactory$Adapter.class:?]
        at com.google.gson.Gson.toJson(Gson.java:669) ~[Gson.class:?]
        at com.google.gson.Gson.toJsonTree(Gson.java:562) ~[Gson.class:?]
        at com.google.gson.Gson.toJsonTree(Gson.java:541) ~[Gson.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[TreeTypeAdapter$GsonContextImpl.class:?]
        at net.minecraft.world.storage.loot.LootTable$Serializer.serialize(LootTable.java:211) ~[bfs$a.class:?]
        at net.minecraft.world.storage.loot.LootTable$Serializer.serialize(LootTable.java:199) ~[bfs$a.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.toJson(Gson.java:669) ~[Gson.class:?]
        at leviathan143.loottweaker.common.lib.LootTableDumper.dump(LootTableDumper.java:50) [LootTableDumper.class:?]
        at leviathan143.loottweaker.common.lib.LootTableDumper.dump(LootTableDumper.java:34) [LootTableDumper.class:?]
        at leviathan143.loottweaker.common.command.SubcommandDumpNamed.execute(SubcommandDumpNamed.java:35) [SubcommandDumpNamed.class:?]
        at leviathan143.loottweaker.common.command.CommandLootTables.executeCommand(CommandLootTables.java:42) [CommandLootTables.class:?]
        at crafttweaker.mc1120.commands.CTChatCommand.execute(CTChatCommand.java:73) [CTChatCommand.class:?]
        at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_231]
        at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`
**Version Info (Exact versions only):**
LootTweaker: 0.1.5
CraftTweaker/Minetweaker: Crafttweaker 2 (4.1.20)
Forge: 1.12.2-14.23.5.2847
Minecraft: 1.12.2
Travellers Backpacks: 1.12.2-1.0.22.22

**Comment by Daomephsta** [comment]
This is an issue with Traveller's Backpacks. Their loot code is weird, I'll open an issue about it on their tracker.

**Comment by Daomephsta** [comment]
Done, see  Tiviacz1337/Travellers-Backpack#85
