### ISSUE TITLE
Unable to dump existing loot tables

### ISSUE THREAD

**Issue by MechanosG** [Leviathan143/LootTweaker#9]
Using either
/mt loottables all
/minetweaker loottables all
outputs this message into chat "An unknown error occurred while attempting to perform this command" and ouputs this into the console

> [15:28:24] [Server thread/WARN]: Couldn't process command: 'mt loottables all'
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3933) ~[guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) ~[guava-17.0.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) ~[bas.class:?]
	at leviathan143.loottweaker.common.lib.LootUtils.writeTableToJSON(LootUtils.java:65) ~[LootUtils.class:?]
	at leviathan143.loottweaker.common.commands.CommandLootTables.execute(CommandLootTables.java:43) ~[CommandLootTables.class:?]
	at minetweaker.MineTweakerImplementationAPI$3.execute(MineTweakerImplementationAPI.java:616) ~[MineTweakerImplementationAPI$3.class:?]
	at minetweaker.mc1102.server.MCServer$MCCommand.func_184881_a(MCServer.java:116) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:104) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:83) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

It also does not show up in "/mt help" properly and cuts off the text.

**Comment by MechanosG** [comment]
Sure, np.
LootTweaker 1.1.5
CraftTweaker 3.0.22
MC version 1.10.2 with forge-12.18.3.2239

Mod list is pretty big and I'm not sure of a way to easily print it.  So I'll manually type it.  AbyssalCraft + Integration, AppleCore, AE2, Auto Sapling, Baubles, Better Combat Mod, BetterFPS, Biomes o Plenty, Block Drops, Bloodmoon, Bookshelf, Botania, Chameleon Creepers, Chat Tweaks, chunkgen, CodeChicken core + lib, Cooking for Blockheads, CraftTweaker (obviously), Custom Main Menu, Dark Utilities, Default Options, Ding, Dooglamoo Cities, Dungeon Tactics, Edible Bugs, Ender IO, EnderCore, FastLeafDecay, Forestry, Futurepack, Gender Mod, Grapple Hooks, Gregtech 5 Unofficial, Hardcore Darkness, HelpFixer (this is supposed to fix help errors like the one I'm getting), Immersive Engineering, Industrial Craft, InfiniteyLib, Java Version Checker, JourneyMap, JurassiCraft, JEI + bunch of extensions, Kaishi's Weapon Pack, LLibrary, Login Shield, LootTweaker, Mantle, McjtyLib, Mekanism, Minecraft Comes Alive, MineTweaker RecipeMaker, ModTweaker (obviously), More Bees, Morpheus, MTLib, Neat, NetherPortalFix, Nomadic Tents, NEI, OpenComputers, Optifine, Overlord, Pam's Harvestcraft, Psi, PSIonic Upgrades, Quark, RadixCore, Regrowable Leaves, Resource Loader, RFTools, RFTools Control, Shadowfacts' Forgelin, ShadowMC, Sleeping Bag, Stalker Creepers, Steve's Factory Manager Reborn, Steve's Inforno, Territorial Dealings, The Spice of Life, Tinker's Construct, TIS-3D, Tomb Many Graves, Waila + extensions, Woot, World Stripper, and finally WTF's Expedition.

Lemme know if you need anymore info.

**Comment by Leviathan143** [comment]
There is no LootTweaker 1.1.5.

**Comment by MechanosG** [comment]
Oops, I read the mod listed under it.  Version is 0.0.3.  Got it off Curse.

**Comment by MechanosG** [comment]
Thanks for the speedy fix!  Now I'll just wait patiently for jar to show up on curse or here.

**Comment by MechanosG** [comment]
Speaking of which..  Any idea when this fix will be uploaded to curse or elsewhere?  No rush.  Just eager to use this for a pack I'm working on with some buddies.

**Comment by Leviathan143** [comment]
@MechanosG There are currently 2 unreleased bugfixes:
* A fix for /mt loottables all not working
* A fix for /mt help not displaying the help for /mt loottables correctly

The first bug only affects the "all" option, the other options work correctly. The second is a tweak to the help text. I consider both minor.

I don't usually upload a new build with this few bugfixes. However I'll do it this time as I'm going to be away from my PC for a few days and because you asked nicely.

**Comment by MechanosG** [comment]
Didn't realize it was only the "all" that was broken on the loot tables option, never tried the others assuming they'd be broken too.  Anyway, thanks for being cool about it.  This fix is much appreciated, even if it's minor.
